repositories:
 - name: bitnami
   url: https://charts.bitnami.com/bitnami

helmDefaults:
  cleanupOnFail: True
  createNamespace: True
  timeout: 1200
  wait: True

releases:
  - name: kafka-prod
    namespace: kafka-prod
    chart: bitnami/kafka
    set:
      - name: image.tag
        value: 3.5.2
      - name: broker.replicaCount
        value: 5
      - name: listeners.client.protocol
        value: SASL_PLAINTEXT
      - name: listeners.interbroker.protocol
        value: SASL_PLAINTEXT

  - name: kafka-dev
    namespace: kafka-dev
    chart: bitnami/kafka
    set:
      - name: image.tag
        value: latest
      - name: broker.replicaCount
        value: 1
      - name: listeners.client.protocol
        value: PLAINTEXT
      - name: listeners.interbroker.protocol
        value: PLAINTEXT
