---
apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: csi-s3-secret
stringData:
  accessKeyID: YCAJEoYI-CpFcX2OKLbpQHQOI
  secretAccessKey: YCP7pfDhARFgE0Q8imZUdL_hbk4oLHbm77IJbq1c
  endpoint: https://storage.yandexcloud.net
