---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.otus.homework.local
spec:
  group: otus.homework.local
  names:
    kind: MySQL
    listKind: MySQLList
    plural: mysqls
    singular: mysql
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: MySQL is the Schema for the mysqls API
        properties:
          apiVersion:
            description: ''
            type: string
          kind:
            description: ''
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of MySQL
            type: object
            properties:
              Image:
                description: 'Определяет docker-образ для создания'
                type: string
              Database:
                description: 'Имя базы данных'
                type: string
              Password:
                description: 'Пароль от БД'
                type: string
              Storage_size:
                description: 'Размер хранилища под БД'
                type: string
          status:
            description: Status defines the observed state of MySQL
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
