apiVersion: v1
kind: Pod
metadata:
  name: hw13
  namespace: homework
  labels:
    app: hw13
spec:
  containers:
  - name: nginx
    image: kyos0109/nginx-distroless
---
apiVersion: v1
kind: Service
metadata:
  name: hw13
  namespace: homework
  labels:
    app: hw13
spec:
  type: ClusterIP
  selector:
    app: hw13
  ports:
  - name: http
    port: 80
    targetPort: 80
