apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-networks
  namespace: default
spec:
  project: otus-kubectl
  source:
    repoURL: https://github.com/Kuber-2023-12OTUS/ntikhomirov_repo.git
    targetRevision: HEAD
    path: kubernetes-networks/
  destination:
    server: https://kubernetes.default.svc
    namespace: homework
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
