# Default values for homework.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: nvtikhomirov/openresty
  tag: otus-2024

############################################
environment:
  name: prod

name: "web"

namespace: homework-prod

rules:
  - rule_url: '/metrics'
    verbs:
      - "get"
      - "list"

serviceAccount: True

service:
  port: 8000
  targetPort: 8000
