---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd
  namespace: homework
secrets:
- name: cd-token
...

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cd
  namespace: homework
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
...

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cd
  namespace: homework
subjects:
- kind: ServiceAccount
  name: cd
  namespace: homework
roleRef:
  kind: Role
  name: cd
  apiGroup: rbac.authorization.k8s.io
...
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: cd
  name: cd-token
  namespace: homework
type: kubernetes.io/service-account-token
...
