---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring
  namespace: homework
...

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: homework
  name: role-monitoring
rules:
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - "get"
      - "list"
...

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-clb
subjects:
- kind: ServiceAccount
  name: monitoring
  namespace: homework
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: role-monitoring
  apiGroup: rbac.authorization.k8s.io
...
