apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-{{ .Values.environment.name | default "test" }}
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.environment.name | default "test" }}.homework.otus
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-{{ .Values.environment.name | default "test" }}
              port:
                number: {{ .Values.service.targetPort | default "8080" }}
