{{- if .Values.serviceAccount -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-{{ .Values.environment.name | default "test" }}
  namespace: {{ .Values.namespace }}
...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-monitoring-{{ .Values.environment.name | default "test" }}
  namespace: {{ .Values.namespace }}
rules:
  {{ range .Values.rules }}
  - nonResourceURLs:
      - {{ .rule_url | quote }}
    verbs:
    {{- range .verbs }}
      - {{ . | quote }}
    {{- end }}
  {{- end }}
...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-clb-{{ .Values.environment.name | default "test" }}
subjects:
- kind: ServiceAccount
  name: monitoring-{{ .Values.environment.name | default "test" }}
  namespace: {{ .Values.namespace }}
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: role-monitoring-{{ .Values.environment.name | default "test" }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
