apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.name }}-storageclass-{{ .Values.environment.name | default "test" }}
  namespace: {{ .Values.namespace }}
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
parameters:
  type: fast
  size: 1Gb
